$schema: "http://json-schema.org/draft-04/schema#"

id: "project"
title: Project
type: object
program: '*'
project: '*'
category: administrative
description: >
  Project is equivalent to Toxicology Investigation a self-contained scientific enquiry composed of studies which generate data or meta-analysis of studies require to have a title and data owner GEO has free-text design description for a series which would be at the project level
additionalProperties: false
submittable: true
validators: null

systemProperties:
  - id
  - geo_accession_number
  - state
  - released
  - public_date
  - submission_date
  - last_update_date
  - releasable
  - intended_release_date
  - design_description

required:
  - code
  - name
  - dbgap_accession_number
  - programs

uniqueKeys:
  - [ id ]
  - [ code ]

links:
  - name: programs
    backref: projects
    label: member_of
    target_type: program
    multiplicity: many_to_one
    required: true

constraints: null

properties:
  type:
    type: string
  id:
    $ref: "_definitions.yaml#/UUID"
    systemAlias: node_id
    description: "UUID for the project." # TOREVIEW
  name:
    type: string
    description: "DNTP project title [investigation:title]"
  design_description:
    type: string
    description: "DNTP design description [investigation:investigation design description]"
  code:
    type: string
    description: "Unique identifier for the project."
  investigator_name:
    description: "Name of the principal investigator for the project."
    type: string
  investigator_affiliation:
    description: "The investigator's affiliation with respect to a research institution."
    type: string
  date_collected:
    description: "The date or date range in which the project data was collected."
    type: string
  availability_type:
    description: "Is the project open or restricted?"
    enum:
      - Open
      - Restricted
  availability_mechanism:
    description: "Mechanism by which the project will be made avilable."
    type: string
  support_source:
    description: "The name of source providing support/grant resources."
    type: string
  support_id:
    description: "The ID of the source providing support/grant resources."
    type: string
  programs:
    $ref: "_definitions.yaml#/to_one"
    description: >
      Indicates that the project is logically part of the indicated project.
  state:
    description: |
      The possible states a project can be in.  All but `open` are
      equivalent to some type of locked state.
    default: open
    enum:
        # open: the only state users can perform 'upload' actions
        # possible actions in `open`:
        #   - upload (no state change)
        #   - review -> review
        #   - release (project.released -> true)
        - open

        # locked: admin has locked project for review
        # possible actions in `locked`:
        #   - open -> open
        #   - submit -> submitted
        #   - release (project.released -> true)
        - review

        # submitted: An admin has submitted project, it is locked against
        #            upload.
        # possible actions in `submitted`:
        #   - process -> processing
        #   - release (project.released -> true)
        - submitted

        # processing: The system is processing data in the project and
        #             is locked against upload and submission
        #   - (system transition to open)
        #   - release (project.released -> true)
        - processing


        # closed: The closed state is introduced to replace the
        #         ``legacy`` state and means that no further action
        #         can be taken on the project
        #   - (system transition to open)
        #   - release (project.released -> true)
        - closed

        # DEPRECATED(2016-03-01): synonymous with closed. included for
        #                         backwards compatibility
        - legacy

  released:
    description: |
      To release a project is to tell the GDC to include all submitted
      entities in the next GDC index [investigation:data publication status:public].
    default: false
    type: boolean

  releasable:
    description: |
      A project can only be released by the user when `releasable` is true.
    default: false
    type: boolean

  release_date:
    description: Tracks a Project's release date [investigation:data publication status:public date].
    type: string
    format: date-time
  
  submission_date:
    description: Tracks a Project's submission date [investigation:data publication status:submit date].
    type: string
    format: date-time

  last_update_date:
    description: Tracks a Project's last update date [investigation:data publication status:last update date].
    type: string
    format: date-time

  intended_release_date:
    description: Tracks a Project's intended release date.
    type: string
    format: date-time
  
  geo_accession_number:
    type: string
    description: "The GEO accession number provided for the project. [investigation:GEO acc no]"
  
  dbgap_accession_number:
    type: string
    description: "The dbgap accession number provided for the project."
