version: '3'
services:

  # requires the TLS_DIR environment variable set to the /Secrets/TLS location under cloud-automation
  # export TLS_DIR=`pwd` in the directory /var/althome/gen3/compose-services or similar

  # requires GEN3_EP environment variable which is the ELB endpoint for the Gen3 portal

  revproxy-service-aws:
    image: "quay.io/cdis/nginx:2021.03"
    container_name: revproxy-service-aws
    networks:
      - devnet
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /var/althome/gen3/compose-services/Secrets/TLS/service.crt:/etc/nginx/ssl/nginx.crt
      - /var/althome/gen3/compose-services/Secrets/TLS/service.key:/etc/nginx/ssl/nginx.key
    ports:
      - "80:80"
      - "443:443"

networks:
  devnet:

